import Navbar from '@/components/navbar';
import './globals.css'
import { inter, workSans, raleway } from "@/styles/fonts";
import Footer from '@/components/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={workSans.className + "scroll-smooth"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
